# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/fpga/bysys3/bysys3.cache/wt [current_project]
set_property parent.project_path D:/Desktop/fpga/bysys3/bysys3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/Desktop/fpga/bysys3/bysys3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Desktop/fpga/bysys3/bysys3.srcs/sources_1/new/decoder38_syn.v
  D:/Desktop/fpga/bysys3/bysys3.srcs/sources_1/new/led.v
  D:/Desktop/fpga/bysys3/bysys3.srcs/sources_1/new/main_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/fpga/bysys3/bysys3.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files D:/Desktop/fpga/bysys3/bysys3.srcs/constrs_1/new/main.xdc]


synth_design -top main_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_top_utilization_synth.rpt -pb main_top_utilization_synth.pb"
